runtime: nodejs20

env_variables:
  MONGODB_URI: "mongodb+srv://thehullfamilysam:cCRS3GsFvmzIy1BW@tarnished-tactics-clust.a0r5gqp.mongodb.net/tarnished-tactics?retryWrites=true&w=majority&appName=tarnished-tactics-cluster"
  NODE_ENV: "production"
  JWT_SECRET: "your-super-secret-jwt-key-here"

automatic_scaling:
  min_instances: 0
  max_instances: 10